POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###
GET http://localhost:3000/Auth

###

POST http://localhost:3000/clock-in
Content-Type: application/json

{
    "userId": "64b9d7de201de63e5d7211f9" 
}