POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###
GET http://localhost:3000/Auth

###

POST http://localhost:3000/clock-in